[tool.poetry]
name = "ds-self-practice"
version = "0.1.0"
description = ""
authors = ["Arist0craft <dimnktn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
